# Generated by Django 6.0.4 on 2026-04-30 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_month', models.PositiveSmallIntegerField()),
                ('reference_year', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('consumption_m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumption_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Atrasado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='companies.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Taxa de imposto (ex: 0.05 para 5%)', max_digits=5)),
                ('late_fee_rate', models.DecimalField(decimal_places=4, default=0, help_text='Multa por atraso (ex: 0.02 para 2%)', max_digits=5)),
                ('daily_interest_rate', models.DecimalField(decimal_places=6, default=0, help_text='Juros diários por atraso', max_digits=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TariffBracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_m3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_m3', models.DecimalField(blank=True, decimal_places=3, help_text='Null = sem limite superior', max_digits=10, null=True)),
                ('price_per_m3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='companies.company')),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='billing.tariffplan')),
            ],
            options={
                'ordering': ['min_m3'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.tariffplan'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'customer', 'reference_month', 'reference_year')},
        ),
    ]
