# Generated by Django 6.0.4 on 2026-04-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='anomaly_flag',
            field=models.BooleanField(default=False),
        ),
    ]
