# Generated by Django 6.0.4 on 2026-04-30 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TRIAL', 'Trial Grátis'), ('BASIC', 'Básico'), ('PRO', 'Profissional'), ('ENTERPRISE', 'Enterprise')], max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Preço anual com desconto (opcional)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_customers', models.PositiveIntegerField(help_text='0 = ilimitado')),
                ('max_meters', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('max_readings_per_month', models.PositiveIntegerField(default=0)),
                ('max_invoices_per_month', models.PositiveIntegerField(default=0)),
                ('has_api_access', models.BooleanField(default=True)),
                ('has_field_app', models.BooleanField(default=False)),
                ('has_reports', models.BooleanField(default=False)),
                ('has_multi_user', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_data_export', models.BooleanField(default=False)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Pagamento Pendente'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='TRIAL', max_length=12)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('VOID', 'Anulado')], default='PENDING', max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_ref', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('customers_count', models.PositiveIntegerField(default=0)),
                ('meters_count', models.PositiveIntegerField(default=0)),
                ('users_count', models.PositiveIntegerField(default=0)),
                ('readings_this_month', models.PositiveIntegerField(default=0)),
                ('invoices_this_month', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='companies.company')),
            ],
        ),
    ]
